name: Puller Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: npm ci
        # npm run build --if-present
        # npm test --if-present

  # deploy:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: testing secret print
  #     env:
  #       CLIENT_ID: ${{ secrets.CLIENT_ID }}
  #       CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  #     run: npm run dev