name: Puller Node CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --only=production
    - run: npm run build --if-present
    - run: npm test

  # deploy:
  #   name: Puller CI Deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: testing secret print
  #     #with: to set the secrets as an input
  #     env:
  #       CLIENT_ID: ${{ secrets.CLIENT_ID }}
  #       CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  #   - run: npm run dev